name: Build My Visual Novel

on:
  push:
    branches: [main]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows
            arch: x86_64
          - os: windows-latest
            target: i686-pc-windows-msvc
            platform: windows
            arch: i686
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            platform: windows
            arch: aarch64
          - os: macos-latest
            target: aarch64-apple-darwin
            platform: macos
            arch: aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            platform: macos
            arch: x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64
          - os: ubuntu-latest
            target: aarch64-linux-android
            platform: android
            arch: aarch64
          - os: ubuntu-latest
            target: armv7-linux-androideabi
            platform: android
            arch: armv7
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            platform: linux
            arch: aarch64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install Java toolchain
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Install Android toolchain
        if: ${{ matrix.platform == 'android' }}
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9477386
      - name: Install Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          # Additional dependencies for ARM64 building
          sudo apt-get install -y xdg-utils
          # Additional dependencies for RPM building
          sudo apt-get install -y rpm
      - name: Install Rustup Android toolchain
        if: ${{ matrix.platform == 'android' }}
        run: |
          rustup target add ${{ matrix.target }}

      - name: install frontend dependencies
        run: npm install

      - name: Build the app
        if: ${{ matrix.platform != 'android' }}
        run: npm run tauri build -- --target ${{ matrix.target }}
      - name: Build Android app and sign app
        if: ${{ matrix.platform == 'android' }}
        run: |
          npm run tauri android init
          # 生成签名（需要调用我的秘密密钥）
          keytool -genkey -v -keystore ~/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass ${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }} -dname "CN=xphost, OU=CandySharkStudio, O=CandySharkStudio, L=BeiJing, ST=BeiJing, C=CN"
          # 生成配置（需要调用我的秘密密钥）
          echo -e "storePassword=${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }}\nkeyPassword=${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }}\nkeyAlias=upload\nstoreFile=/home/runner/upload-keystore.jks" >> src-tauri/gen/android/keystore.properties
          # 修改 build.gradle.kts
          # 首行新增一行 import
          sed -i '1i import java.io.FileInputStream' src-tauri/gen/android/app/build.gradle.kts
          # 随后找到 buildType 那一行的往上新增一句话。
          sed -i '/buildType/isigningConfigs {\ncreate("release") {\nval keystorePropertiesFile = rootProject.file("keystore.properties")\nval keystoreProperties = Properties()\nif (keystorePropertiesFile.exists()) {\nkeystoreProperties.load(FileInputStream(keystorePropertiesFile))\n}\nkeyAlias = keystoreProperties["keyAlias"] as String\nkeyPassword = keystoreProperties["keyPassword"] as String\nstoreFile = file(keystoreProperties["storeFile"] as String)\nstorePassword = keystoreProperties["storePassword"] as String\n}\n}' src-tauri/gen/android/app/build.gradle.kts
          # 最后在 getByName("release") 底下新增一行，完事！
          sed -i '/getByName("release")/asigningConfig = signingConfigs.getByName("release")' src-tauri/gen/android/app/build.gradle.kts
          # 最后再开始打包 Android。。 开始构建！！
          npm run tauri android build -- --target ${{ matrix.arch }}
      - name: Upload artifact Windows
        if: ${{matrix.platform == 'windows'}}
        uses: actions/upload-artifact@v4
        with:
          name: Bundle-${{matrix.platform}}-${{matrix.arch}}
          path: "src-tauri/target/${{ matrix.target }}/release/awakeofruin.exe"
          if-no-files-found: error

      - name: Upload artifact linux
        if: ${{matrix.platform == 'linux'}}
        uses: actions/upload-artifact@v4
        with:
          name: Bundle-${{matrix.platform}}-${{matrix.arch}}
          path: "src-tauri/target/${{ matrix.target }}/release/awakeofruin"
          if-no-files-found: error

      - name: Upload artifact macOS
        if: ${{matrix.platform == 'macos'}}
        uses: actions/upload-artifact@v4
        with:
          name: Bundle-${{matrix.platform}}-${{matrix.arch}}
          path: "src-tauri/target/${{ matrix.target }}/release/bundle/macos"
          if-no-files-found: error
      - name: Upload artifact android
        if: ${{matrix.platform == 'android'}}
        uses: actions/upload-artifact@v4
        with:
          name: Bundle-${{matrix.platform}}-${{matrix.arch}}
          path: "src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk"
          if-no-files-found: error
